basicLocaleListResolution is throwing a imported from multiple packages conflict error
Error: 'basicLocaleListResolution' is imported from both 'package:flutter/src/widgets/app.dart' and 'package:device_preview/src/locales/locales.dart'.

Resolved the by specifying the import should be from locales.dart and not flutter's app.dart